AllCops:
  Exclude:
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'Guardfile'
    - 'db/schema.rb'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'

Style/Documentation:
  Enabled: false

Style/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
